Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -36,10 +36,10 @@ jobs:
         run: |
           sudo apt-get update
           sudo apt-get install libappindicator3-1
-          curl -L -o google-chrome.deb https://github.com/webnicer/chrome-downloads/raw/master/x64.deb/${CHROME_VERSION}/google-chrome-stable_${CHROME_VERSION}_amd64.deb
+          curl -L -o google-chrome.deb https://github.com/webnicer/chrome-downloads/raw/master/x64.deb/${{ env.CHROME_VERSION }}/google-chrome-stable_${{ env.CHROME_VERSION }}_amd64.deb
       - name: test
         run: |
           sudo dpkg -i google-chrome.deb
           # get version and assert if it's the same as the one we want to install
-          [ "$(google-chrome --version 2>&1 | awk '{print $3}')" == "${CHROME_VERSION}" ] || { echo "Error: Chrome version does not match the desired version."; exit 1; }
+          [ "$(google-chrome --version 2>&1 | awk '{print $3}')" == "${{ env.CHROME_VERSION }}" ] || { echo "Error: Chrome version does not match the desired version."; exit 1; }
           
